### ISSUE TITLE
Black/isort precommits for Python; prettier for JS?

### ISSUE THREAD

**Issue by CodyCBakerPhD** [garrettmflynn/webnwb-benchmark#2]
For making code more standard to the NWB Benchmarks (all Python) repo

**Comment by garrettmflynn** [comment]
Do we want to move this to the main NWB Benchmarks repo at some point? Just curious whether we're tidying this up before migration or if this repo will be the home of these features

**Comment by CodyCBakerPhD** [comment]
I think the plan is for this to all move to NWB Benchmarks repo, yes

But that move will be cleaner if the code to be moved is cleaner as well
